[package]
name = "sbs-rust-contentapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["handlebars"] }
reqwest = { version = "0.11", default-features=false, features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_qs = "0.10"
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
chrono = { version = "0.4", features = ["serde"] }