[package]
name = "sbs-rust-contentapi"
version = "0.3.0"
edition = "2021"

[workspace]
members = [ "bbcode", "contentapi", "pages" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
warp = { version = "0.3", default-features = false, features = ["multipart"]}
# axum = { version = "0.6.1", features = ["multipart", "http2","headers"] }
serde = { version = "1", features = ["derive"] }
# tower-cookies = { version = "0.8" }
toml = "0.5.9"

contentapi = { path = "contentapi" }
bbcode = { path = "bbcode" }
pages = { path = "pages" }