[package]
name = "warp-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
# tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", default-features = false, features = ["multipart"]}
reqwest = { version = "0.11", default-features=false, features = ["json","multipart","stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
# serde_with = "2.1"
serde-aux = "4.1.2"
regex = "1.0"
maud = "0.24.0"
# handlebars = "4.3.5"
html-escape = "0.2.12"
# thiserror = "1.0.37"
# strum_macros = "0.24.3"
# tempfile = "3.3.0"