# This is the contentapi endpoint for the frontend, should point to SBS!
api_endpoint = "http://localhost:5000/api"  # contentapi by default hosts on port 5000
http_root = "" #Don't want double forwardslash
api_fileraw = "/contentapi/images"
host_address = "127.0.0.1:5011" # Localhost:5011, but you can change it to whatever (0.0.0.0 for global?)

# The rest is whatever
token_cookie_key = "sbs_contentapi_token"
default_cookie_expire = 1209600 #14 days in seconds
long_cookie_expire = 31536000 # 365 days in seconds
default_imagebrowser_count = 100
default_category_threads = 1  # threads to show in category view
default_display_threads = 50  # threads to show per page 
default_display_posts = 20  # posts to show per page (on threads)


# Special SBS stuff (may store in database instead?)
# Category order is a "starts with" matching for order
forum_category_order = ["Programming", "FAQ", "General", "Talk", "SmileBASIC Bug", "Site"]

# file limit is 10 MB, but server will resize as necessary
body_maxsize = 10000000
