[package]
name = "pages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.24.0"
serde_urlencoded = "0.7.1"
serde_json = "1.0"

contentapi = { path = "../contentapi" }